name: 07 - Using Expressions
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                description: 'Debug mode'
                type: boolean   
                required: false
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            name: [debug] Print start-up data
            if: ${{ inputs.debug == true }}
            run: |
                echo "Triggered by: ${{ github.event_name}}"
                echo: "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"