name: 09 - Using Functions
on: 
    pull_request:
    workflow_dispatch:
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Failing step
              run: |
                exit 1
            - name: I will be skipped
              if: success()
              run: |
                echo "I will be skipped"
            - name: I will execute
              if: always()
              run: |
                echo "I will execute"
            - name: I will execute
              if: !cancelled()
              run: |
                echo "I  will always print, except when the workflow is cancelled."

