name: 12 - Working with Outputs
on:
    workflow_dispatch:
        inputs:
            build_status:
                type: choice
                options:
                    - success
                    - failure
                default:
                    success
                description: 'The status of the build'

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
            output1: "output1"
        steps:
            - name: Print GITHUB_OUTPUT path
              run: |
                echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"
            - name: build
              id: build
              run: |
                echo "status=${{ github.event.inputs.build_status }}" >> $GITHUB_OUTPUT
                echo "output1=value1" >> $GITHUB_OUTPUT
                echo "output2=value2" >> $GITHUB_OUTPUT
                cat $GITHUB_OUTPUT
                echo "mistake=true" > "$GITHUB_OUTPUT"
                cat $GITHUB_OUTPUT
    deploy:
        if: ${{ success() && needs.build.outputs.build-status == 'success' }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy
              run: |
                echo "Deploying"
            - name: Print outputs
              run: |
                echo "output1 = ${{ needs.build.outputs.output1 }}"