name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                description: Use cache
                default: true
            node-version:
                type: choice
                options:
                - '18.x'
                - '20.x'
                - '21.x'
                default: '20.x'
                description: Node version
jobs:
    install-deps:
        runs-on: ubuntu-latest
        defaults:
          run: 
            working-directory: 04-using-actions/react-app
        outputs:
          deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          
          - name: Setup Node
            uses: actions/setup-node@v2
            with:
              node-version: ${{ github.event.inputs.node-version }}
                  
          - name: Calculate cache key
            id: cache-key
            run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('04-using-actions/react-app/package-lock.json') }}" >> $GITHUB_OUTPUT
          
          - name: Download Cache Dependencies
            if: ${{ github.event.inputs.use-cache }}
            id: cache-new
            uses: actions/cache@v3
            with: 
              path: 04-using-actions/react-app/node_modules
              key: ${{ steps.cache-key.outputs.CACHE_KEY }}
          
          - name: Install Dependencies
            if: steps.cache-new.outputs.cache-hit != 'true'
            run: npm ci
    build:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
          run: 
            working-directory: 04-using-actions/react-app
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          
          - name: Setup Node
            uses: actions/setup-node@v2
            with:
              node-version: ${{ github.event.inputs.node-version }}
          
          - name: Download Cache Dependencies
            if: ${{ github.event.inputs.use-cache }}
            id: cache
            uses: actions/cache@v3
            with: 
              key: ${{ needs.install-deps.outputs.deps-cache-key }}
              path: 04-using-actions/react-app/node_modules
          
         
          - name: Testing
            run: npm test
          
          - name: Building
            run: npm run build
          
          - name: Deploying to Nonprod
            run: echo "Deploying to Nonprod"
    
    Linting:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
          run:
            working-directory: 04-using-actions/react-app
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ github.event.inputs.node-version }}
        - name: Download Cache Dependencies
          if: ${{ github.event.inputs.use-cache }}
          id: cache
          uses: actions/cache@v3
          with: 
            key: ${{ needs.install-deps.outputs.deps-cache-key }}
            path: 04-using-actions/react-app/node_modules
        - name: Linting
          run: npm run lint


            