name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                description: Use cache
                default: true
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run: 
            working-directory: 13-using-caching/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm ci
            - name: Testing
              run: npm test
            - name: Building
              run: npm run build
            - name: Deploying to Nonprod
              run: echo "Deploying to Nonprod"

            