name: 15 - Working with Matrices
on:
    workflow_dispatch:
jobs:
    backward-compatibility:
        name: ${{ matrix.os }}-${{ matrix.node-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os: [ubuntu-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental

        steps:
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
            - name: Fail if experimental
              if: matrix.tag == 'experimental'
              run: |
                exit 1
            - name: Perform Some Tests
              run: |
                echo "Running tests on OS ${{ matrix.os }} with Node version ${{ matrix.node-version }}"
                sleep 10
            - name: Upload Test Results
              run: |
                echo "Uploading test results"
    include-example:
        name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}- ${{ matrix.opacity }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                color:
                    - red
                    - green
                shape:
                    - square
                    - circle
                size:
                    - small
                    - large
                include:
                    - opacity: 50
                    - color: red
                      shape: triangle
        
        steps:
            - name: Dummy Step
              run: |
                echo "Running tests on ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
        

    
    
