name: 16 - Working with Environments
# run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}
on:
    workflow_dispatch:
        
jobs:
    deploy_staging:
        runs-on: ubuntu-latest
        environment: staging
        env:
            MY_ENV_VALUE: ${{ vars.MY_ENV_VALUE || 'default_value' }}
        steps:
            - name: Echo vars
              run: |
                echo "Env variable: ${{ env.MY_ENV_VALUE }}"