name: 18 - 1 - Reusable Workflows - Reusable Definition
on: 
    workflow_call:
        inputs:
            target-directory:
                type: string
                required: true
        outputs: # Define the outputs of the workflow from the jobs to be used by caller workflows
            build-status:
                description: The status of the build process
                value: ${{ jobs.deploy.outputs.status }}
            url:
                description: The URL of the deployed application
                value: ${{ jobs.deploy.outputs.url }}
jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs: # Declares the outputs of the job from the steps in the job
            status: ${{ steps.build.outputs.build-status }}
            url: ${{ steps.deploy.outputs.url }}
        steps:
            - uses: actions/checkout@v4
              name: Checkout repo
            
            - name: Build
              id: build
              run: |
                echo "Building using directory ${{ inputs.target-directory }}"
                echo "build-status=success" >> $GITHUB_OUTPUT
            
            - name: Deploy
              id: deploy
              run: |
                echo "Deploying build artifacts"
                echo "url=https://www.google.com" >> $GITHUB_OUTPUT
