name: 18 - 1 - Reusable Workflows - Reusable Definition
on: 
    workflow_call:
        inputs:
            target-directory:
                type: string
                required: true
        outputs:
            build-status:
                description: The status of the build process
                value: ${{ steps.deploy.outputs.status }}
            url:
                description: The URL of the deployed application
                value: ${{ steps.deploy.outputs.url }}
jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            status: ${{ job.status }}
            url: ${{ steps.deploy.outputs.url }}
        steps:
            - uses: actions/checkout@v2
              name: Checkout repo
            - name: Build
              run: |
                echo "Building using directory ${{ inputs.target-directory }}"
                echo "build-status=success" >> $GITHUB_ENV
            - name: Deploy
              id: deploy
              run: |
                echo "Deploying build artifacts"
                echo "url=https://www.google.com" >> $GITHUB_ENV
