name: 18 - 3 - Reusable Workflows
on: 
    workflow_dispatch:
jobs:
    deploy:
      uses: ./.github/workflows/18-1-reusable-workflows.yaml
      with:
        target-directory: 'deploy'
        e2e-tests:
        needs: deploy
        uses: greg-greenlee/github-actions-course-example-e2e/.github/workflows/e2e.yaml@main